module.exports = {
    designersAvailable: 'socket:designers:available',
    authenticate: 'socket:authenticate',
    chatStatus: 'socket:update:chatStatus',
    userOffline: 'socket:user:offline',
    userJoinChats: 'socket:user:join',
    typing: 'socket:update:typing',
    requestChat: 'socket:request:chat',
    instigateChat: 'socket:start:chat',
    inviteUserToChat: 'socket:invite:user',
    userJoinedChat: 'socket:chat:userJoined',
    socketId: 'socket:socketId',
    leaveRoom: 'socket:leaveRoom',
    userLeftRoom: 'socket:userLeftRoom',
    chatMessage: 'socket:chat:message',
    userIsTyping: 'socket:chat:isTyping',
    userStoppedTyping: 'socket:chat:stoppedTyping',
    usersOnline: 'socket:users:online',
    newProject: 'socket:project:new',
    updateProjectAddress: 'socket:project:update:address',
    removeProject: 'socket:project:remove',
    updateProject: 'socket:project:update',
    projects: 'socket:projects',
    newDesignbrief: 'socket:project:brief:new',
    updateDesignbrief: 'socket:project:brief:update',
    lockBrief: 'socket:project:brief:lock',
    terms:'socket:terms',
    termsStream:'socket:stream:terms',
    attachmentsForProjectGuid: 'socket:project:attachments:new'
};